### ISSUE TITLE
如果使用 DTAttributedTextContentView 而不是 DTAttributedTextCell 

### ISSUE THREAD

**Issue by MikeChongCan** [Jeswang/load-cell-image#1]
您好，我是 https://www.v2ex.com/t/157760 的楼主。感谢您的回复，您提供的思路基本能避免循环加载。但是自己在实际应用中还是有很大的问题：
我改用了 DTAttributedTextContentView ，如下
https://github.com/imWildCat/load-cell-image/blob/1b6bfcee34e19900f6c0aad0c30760345a5d608e/load-cell-image/ImageTableViewController.m#L107-L110
但是问题来了， 如果横屏再切回来，整个显示就不正常了，前几个 cell 会不显示。

而且我在自己的项目里使用这个，横屏再切回来会导致图片都无法显示（包括图片所在的 cell），很纠结。

**Comment by Jeswang** [comment]
现在的代码 relayout 有点太频繁了，缓存的信息也有点繁琐，晚些时候我再改改看。
另外，你给我看的代码的 83-86 删除了行高的获取，我不确定这样的机制有没有问题。

**Comment by MikeChongCan** [comment]
@Jeswang  Thanks!
自己写了段计算行高的代码:

``` objective-c
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath{
    CoreTextTableViewCell *cell = [self tableView:tableView preparedCellForIndexPath:indexPath];

    CGFloat width = cell.attributedTextContextView.frame.size.width;
    CGFloat suggestedHeight = [cell.attributedTextContextView suggestedFrameSizeToFitEntireStringConstraintedToWidth:width].height;

    return suggestedHeight + 10.0;
}
```

不知为何有运行时错误。

我不着急，你就方便的时候看即可。

**Comment by wonderffee** [comment]
频繁调用[self.tableView reloadData];肯定有问题，而且图片加载完成后还不能自适应屏幕宽度，都能显示在屏幕右边了。。。

**Comment by wonderffee** [comment]
https://github.com/notjosh/SkitchThat/blob/master/SkitchThat/ObjectViewController.m
上面这个链接里面可能更全一点
